service: serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: development
  region: ap-southeast-1
  environment:
    TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  createNote:
    handler: apis/handler.create
    memorySize: 128
    description: Create note from lambda
    events:
      - http:
          path: create
          method: POST
  listNotes:
    handler: apis/handler.listNotes
    memorySize: 128
    description: List all notes
    events:
      - http:
          path: notes
          method: GET
  noteDetails:
    handler: apis/handler.noteDetails
    events:
      - http:
          path: notes/{id}
          method: GET



resources:
  Resources:
    NotesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.TABLE}